// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQtsSfz-0U5TN819Yl6rd6jKb89fJMYHM',
    appId: '1:179786751607:web:6f4c44a480bdbb0faa3072',
    messagingSenderId: '179786751607',
    projectId: 'contract-78fb1',
    authDomain: 'contract-78fb1.firebaseapp.com',
    databaseURL: 'https://contract-78fb1-default-rtdb.firebaseio.com',
    storageBucket: 'contract-78fb1.appspot.com',
    measurementId: 'G-81KXQCKR24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWU3_VrtZASrePGnQBV74W3ol-BJycPI',
    appId: '1:179786751607:android:07551ae8e0695c72aa3072',
    messagingSenderId: '179786751607',
    projectId: 'contract-78fb1',
    databaseURL: 'https://contract-78fb1-default-rtdb.firebaseio.com',
    storageBucket: 'contract-78fb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtcLRzGp2TXtWD_fDFAFqj5L1n3WNyFvg',
    appId: '1:179786751607:ios:1bee79a98853ecdeaa3072',
    messagingSenderId: '179786751607',
    projectId: 'contract-78fb1',
    databaseURL: 'https://contract-78fb1-default-rtdb.firebaseio.com',
    storageBucket: 'contract-78fb1.appspot.com',
    iosBundleId: 'com.example.form',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtcLRzGp2TXtWD_fDFAFqj5L1n3WNyFvg',
    appId: '1:179786751607:ios:55a4743b3dbb8280aa3072',
    messagingSenderId: '179786751607',
    projectId: 'contract-78fb1',
    databaseURL: 'https://contract-78fb1-default-rtdb.firebaseio.com',
    storageBucket: 'contract-78fb1.appspot.com',
    iosBundleId: 'com.example.form.RunnerTests',
  );
}
